import type { Metadata } from "next";

export const links = {
  sourceCode: "https://github.com/sanidhyy/next-portfolio",
  ownerName: "Nguyễn Đinh Anh Trường",
  ownerEmail: "ndatruong@vishipel.com.vn",
  cvLink: "https://daihoc.fpt.edu.vn/en/wp-content/uploads/2022/08/RESFES-2021_Program-_-Abstract.pdf",
  researchPaper: "https://dl.acm.org/doi/abs/10.1145/3556223.3556239",
} as const;

export const siteConfig: Metadata = {
  title: `${links.ownerName}'s Portfolio`,
  description: "Chuyên viên Công ty TNHH MTV Thông tin Điện tử Hàng hải Việt Nam - 4 năm kinh nghiệm phát triển phần mềm",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "aceternity",
    "aceternity-ui",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "modern-portfolio",
    "portfolio",
    "3d-portfolio",
    "animated-portfolio",
    "nextjs-portfolio",
    "react-portfolio",
    "react-three-fiber",
    "three.js",
    "animated-website",
    "framer",
    "framer-motion",
    "three",
    "react-icons",
    "lucide-react",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: links.ownerName,
    url: "https://www.cake.me/nguyen-dinh-anh-truong",
  },
} as const;
